"""add application preparations

Revision ID: 2eb6029c7298
Revises: 410ac929ca79
Create Date: 2026-08-25 12:16:37.482533

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2eb6029c7298"
down_revision: str | Sequence[str] | None = "410ac929ca79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_preparations",
        sa.Column("preparation_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("agent_engine_job_id", sa.String(length=128), nullable=False),
        sa.Column("agent_engine_thread_id", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status IN ('pending', 'starting') AND agent_engine_thread_id IS NULL AND error_message IS NULL) OR (status IN ('awaiting_review', 'completed') AND agent_engine_thread_id IS NOT NULL AND error_message IS NULL) OR (status IN ('failed', 'outcome_unknown') AND agent_engine_thread_id IS NULL AND error_message IS NOT NULL)",
            name="ck_application_preparations_state",
        ),
        sa.CheckConstraint(
            "agent_engine_thread_id IS NULL OR btrim(agent_engine_thread_id) <> ''",
            name="ck_application_preparations_thread_id_not_blank",
        ),
        sa.CheckConstraint(
            "btrim(agent_engine_job_id) <> ''",
            name="ck_application_preparations_job_id_not_blank",
        ),
        sa.CheckConstraint(
            "btrim(user_id) <> ''", name="ck_application_preparations_user_id_not_blank"
        ),
        sa.CheckConstraint(
            "error_message IS NULL OR btrim(error_message) <> ''",
            name="ck_application_preparations_error_not_blank",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'starting', 'awaiting_review', 'completed', 'failed', 'outcome_unknown')",
            name="ck_application_preparations_status",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["job_applications.application_id"],
        ),
        sa.PrimaryKeyConstraint("preparation_id"),
        sa.UniqueConstraint(
            "agent_engine_job_id", name="uq_application_preparations_agent_engine_job"
        ),
        sa.UniqueConstraint(
            "application_id", name="uq_application_preparations_application"
        ),
    )
    op.create_index(
        "ix_application_preparations_user_status",
        "application_preparations",
        ["user_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_application_preparations_user_status", table_name="application_preparations"
    )
    op.drop_table("application_preparations")
    # ### end Alembic commands ###
