"""add idempotency records

Revision ID: 410ac929ca79
Revises: b973bbb7b6fc
Create Date: 2026-08-19 18:03:25.443803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "410ac929ca79"
down_revision: str | Sequence[str] | None = "b973bbb7b6fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "btrim(idempotency_key) <> ''", name="ck_idempotency_records_key_not_blank"
        ),
        sa.CheckConstraint(
            "btrim(user_id) <> ''", name="ck_idempotency_records_user_id_not_blank"
        ),
        sa.CheckConstraint(
            "operation IN ('create_application', 'update_application_status')",
            name="ck_idempotency_records_operation",
        ),
        sa.CheckConstraint(
            "(response_payload IS NULL AND completed_at IS NULL) OR (response_payload IS NOT NULL AND completed_at IS NOT NULL)",
            name="ck_idempotency_records_completion_state",
        ),
        sa.CheckConstraint(
            "char_length(request_fingerprint) = 64",
            name="ck_idempotency_records_fingerprint_length",
        ),
        sa.PrimaryKeyConstraint("user_id", "operation", "idempotency_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
