"""add application review submissions

Revision ID: b2df53836a53
Revises: 2eb6029c7298
Create Date: 2026-08-25 20:58:22.874794

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b2df53836a53"
down_revision: str | Sequence[str] | None = "2eb6029c7298"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_review_submissions",
        sa.Column("review_submission_id", sa.UUID(), nullable=False),
        sa.Column("preparation_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column(
            "approved_proposal_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "rejected_proposal_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("edits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewer_comment", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status IN ('pending', 'submitting') AND outcome IS NULL AND error_message IS NULL) OR (status = 'completed' AND outcome IS NOT NULL AND error_message IS NULL) OR (status IN ('failed', 'outcome_unknown') AND outcome IS NULL AND error_message IS NOT NULL)",
            name="ck_application_review_submissions_state",
        ),
        sa.CheckConstraint(
            "action IN ('approve', 'edit', 'reject', 'regenerate')",
            name="ck_application_review_submissions_action",
        ),
        sa.CheckConstraint(
            "btrim(action) <> ''",
            name="ck_application_review_submissions_action_not_blank",
        ),
        sa.CheckConstraint(
            "btrim(idempotency_key) <> ''",
            name="ck_application_review_submissions_key_not_blank",
        ),
        sa.CheckConstraint(
            "btrim(thread_id) <> ''",
            name="ck_application_review_submissions_thread_id_not_blank",
        ),
        sa.CheckConstraint(
            "btrim(user_id) <> ''",
            name="ck_application_review_submissions_user_id_not_blank",
        ),
        sa.CheckConstraint(
            "error_message IS NULL OR btrim(error_message) <> ''",
            name="ck_application_review_submissions_error_not_blank",
        ),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('awaiting_review', 'completed')",
            name="ck_application_review_submissions_outcome",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'submitting', 'completed', 'failed', 'outcome_unknown')",
            name="ck_application_review_submissions_status",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["job_applications.application_id"],
        ),
        sa.ForeignKeyConstraint(
            ["preparation_id"],
            ["application_preparations.preparation_id"],
        ),
        sa.PrimaryKeyConstraint("review_submission_id"),
        sa.UniqueConstraint(
            "user_id",
            "idempotency_key",
            name="uq_application_review_submissions_user_key",
        ),
    )
    op.create_index(
        "ix_application_review_submissions_preparation",
        "application_review_submissions",
        ["preparation_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_application_review_submissions_preparation",
        table_name="application_review_submissions",
    )
    op.drop_table("application_review_submissions")
    # ### end Alembic commands ###
