"""create application operations tables

Revision ID: b973bbb7b6fc
Revises:
Create Date: 2026-08-17 22:31:34.408895

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b973bbb7b6fc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_applications",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("role_title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "btrim(company_name) <> ''",
            name="ck_job_applications_company_name_not_blank",
        ),
        sa.CheckConstraint(
            "btrim(role_title) <> ''", name="ck_job_applications_role_title_not_blank"
        ),
        sa.CheckConstraint(
            "btrim(user_id) <> ''", name="ck_job_applications_user_id_not_blank"
        ),
        sa.CheckConstraint(
            "status IN ('saved', 'preparing', 'ready_to_apply', 'applied', 'interviewing', 'offer', 'rejected', 'withdrawn', 'closed')",
            name="ck_job_applications_status",
        ),
        sa.PrimaryKeyConstraint("application_id"),
    )
    op.create_index(
        "ix_job_applications_user_status",
        "job_applications",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "action_items",
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "action_type IN ('review_cv', 'submit_application', 'follow_up', 'check_status', 'prepare_interview', 'record_outcome')",
            name="ck_action_items_action_type",
        ),
        sa.CheckConstraint(
            "btrim(description) <> ''", name="ck_action_items_description_not_blank"
        ),
        sa.CheckConstraint(
            "btrim(user_id) <> ''", name="ck_action_items_user_id_not_blank"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'cancelled')",
            name="ck_action_items_status",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["job_applications.application_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    op.create_index(
        "ix_action_items_user_status_due",
        "action_items",
        ["user_id", "status", "due_at"],
        unique=False,
    )
    op.create_table(
        "application_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "btrim(actor_id) <> ''", name="ck_application_events_actor_id_not_blank"
        ),
        sa.CheckConstraint(
            "btrim(user_id) <> ''", name="ck_application_events_user_id_not_blank"
        ),
        sa.CheckConstraint(
            "event_type IN ('application_created', 'status_changed')",
            name="ck_application_events_event_type",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["job_applications.application_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_application_events_application_occurred",
        "application_events",
        ["application_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "approval_requests",
        sa.Column("approval_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "action_type IN ('submit_application', 'send_external_message', 'create_external_calendar_event')",
            name="ck_approval_requests_action_type",
        ),
        sa.CheckConstraint(
            "btrim(requested_by) <> ''",
            name="ck_approval_requests_requested_by_not_blank",
        ),
        sa.CheckConstraint(
            "btrim(user_id) <> ''", name="ck_approval_requests_user_id_not_blank"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired')",
            name="ck_approval_requests_status",
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > created_at",
            name="ck_approval_requests_expiry_after_creation",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["job_applications.application_id"],
        ),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index(
        "ix_approval_requests_user_status",
        "approval_requests",
        ["user_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_approval_requests_user_status", table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(
        "ix_application_events_application_occurred", table_name="application_events"
    )
    op.drop_table("application_events")
    op.drop_index("ix_action_items_user_status_due", table_name="action_items")
    op.drop_table("action_items")
    op.drop_index("ix_job_applications_user_status", table_name="job_applications")
    op.drop_table("job_applications")
    # ### end Alembic commands ###
